apiVersion: v1
kind: Pod
metadata:
  name: test1
spec:
  containers:
  - name: postgre-db
    image: martiii1/scraper_postgre_db:latest
    ports:
    - containerPort: 5432
  - name: emag-scraper
    image: martiii1/emag_scraper:latest
    env:
    - name: env_host
      value: "192.168.49.2"
    - name: env_name
      value: "test1"
    - name: env_pass
      value: "postgres"
    - name: env_port
      value: "5432"
    - name: env_table_name
      value: "slushalki_prices"
    - name: env_user
      value: "postgres"
